central: http://host.docker.internal:5006
services:
  dataset:
    hyper_kvasir: http://host.docker.internal:5002
  model:
    effnetv2s: http://host.docker.internal:5001
  model_evaluation:
    model_eval: http://host.docker.internal:5005

configuration:
  dataset:
    - name: basic_dataset_config
      content: |
        img_size: 128
        batch_size: 128
        data_loader_kwargs:
          num_workers: 0
    - name: cutmix_dataset_config
      content: |
        img_size: 128
        batch_size: 128
        data_loader_kwargs:
          num_workers: 0
        mixed_aug_with_target_and_model:
          - backend_central_dev.data_processing.mix.CutMixUp
          - prob: 1.0
    - name: puzzlemix_dataset_config
      content: |
        img_size: 128
        batch_size: 128
        data_loader_kwargs:
          num_workers: 0
        mixed_aug_with_target_and_model:
          - backend_central_dev.data_processing.mix.PuzzleMix
          - prob: 1.0

  model:
    - name: basic_model_config
      content: |
        model_key: pytorch_efficientnet_v2_s
        optimizer_hparams: {
          lr: 0.0001,
          weight_decay: 4.0e-5
        }
        lr_scheduler_key: MultiStepLR
        lr_scheduler_hparams: { milestones: [45, 65], gamma: 0.1 }
  trainer:
    - name: basic_trainer_config
      content: |
        callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args:
            monitor: val_acc
            save_top_k: 1
            filename: best-{epoch}-{val_acc:.4f}
            mode: max
            save_weights_only: True
        max_epochs: 80
    - name: quick_trainer_config
      content: |
        max_epochs: 1
        max_steps: 1

task_sheet:
  training:
    - name: quick_training_task
      db_service: hyper_kvasir
      model_service: effnetv2s
      dataset_config: [basic_dataset_config]
      model_config: basic_model_config
      trainer_config: quick_trainer_config
      task_function_key: training
      
    - name: quick_cutmix_training_task
      db_service: hyper_kvasir
      model_service: effnetv2s
      dataset_config: [cutmix_dataset_config]
      model_config: basic_model_config
      trainer_config: quick_trainer_config
      task_function_key: training
      
    - name: quick_puzzlemix_training_task
      db_service: hyper_kvasir
      model_service: effnetv2s
      dataset_config: [puzzlemix_dataset_config]
      model_config: basic_model_config
      trainer_config: quick_trainer_config
      task_function_key: training
      
  # model_evaluation:
  #   - name: basic_model_evaluation_task
  #     db_service: hyper_kvasir
  #     model_service: effnetv2s
  #     model_evaluation_service: model_eval
  #     dataset_config: [basic_dataset_config]
  #     model_config: basic_model_config
  #     trainer_config: basic_trainer_config
  #     task_function_key: macro_acc_eval
# pipeline_sheet:
#   training_pipeline:
#     - name: basic_training_pipeline
#       train: basic_training_task
#       model_evaluation: basic_model_evaluation_task
