name: Deploy MLOps Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Free disk space
      run: |
        # Display initial disk space
        df -h
        
        # Remove unnecessary large packages
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/local/lib/android
        
        # Clear Docker cache
        docker system prune -af
        
        # Clear apt cache
        sudo apt clean
        
        # Display free space after cleanup
        df -h
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Create Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo '{
          "username": "${{ secrets.KAGGLE_USERNAME }}",
          "key": "${{ secrets.KAGGLE_KEY }}"
        }' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        
        echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" > .kaggle.env
        echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> .kaggle.env
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build central service
      run: docker compose --env-file ./.kaggle.env -f docker-compose.yaml build central
      
    - name: Start central service
      run: docker compose --env-file ./.kaggle.env -f docker-compose.yaml up central -d
      
    - name: Build dataset and model services
      run: docker compose --env-file ./.kaggle.env -f docker-compose.yaml build effnetv2s hyperk
      
    - name: Start dataset and model services
      run: docker compose --env-file ./.kaggle.env -f docker-compose.yaml up effnetv2s hyperk -d
      
    - name: Register and apply SDK configurations
      run: |
        python ./mlxops_sdk.py -f ./sdk_config/docker_local.yml reg
        python ./mlxops_sdk.py -f ./sdk_config/docker_local.yml apply
        python ./mlxops_sdk.py -f ./sdk_config/docker_local.yml ts apply
      
    - name: Build web frontend
      run: docker compose -f docker-compose.yaml build web
      
    - name: Start web frontend
      run: docker compose -f docker-compose.yaml up web -d
      
    - name: Build model evaluation service
      run: docker compose --env-file ./.kaggle.env -f docker-compose.yaml build model_eval
      
    - name: Start model evaluation service
      run: docker compose --env-file ./.kaggle.env -f docker-compose.yaml up model_eval -d
      
    - name: Check running containers
      run: docker ps -a
